### PR TITLE
adds q

### PR DESCRIPTION
**Pull request by thereactgirl**
# Description
[Trello Card
](https://trello.com/c/xMGG98zF)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update

# How Has This Been Tested?

- [x] Yes
- [ ] No

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added documentation to complex files
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by thereactgirl** [comment]
What do you think @TurkeyFats

**Comment by thereactgirl** [comment]
What do you think @castzad ?

**Review by TurkeyFats — APPROVED** [review]

**Review by castzad — APPROVED** [review]
Fine I approve

**Review by castzad — APPROVED** [review]
Approved

**Review by castzad — CHANGES_REQUESTED** [review]
Unapproved

**Review by castzad — APPROVED** [review]
Reapproved

**Pull request closed without merging**
